module.exports = {

    navLinks: [
        {
            name: 'Introduction',
            url: '/#landing',
        },
        {
            name: 'Getting Started',
            url:'/#get-started',
        },
        {
            name: 'Installation',
            url:'/#install',
        },
        {
            name: 'FAQ',
            url:'/#faq',
        }
    ],

    landingItems: [
        {
            header: "What Is Custom Water Cooling?",
            body: "Custom water cooling is a method of cooling computer components, such as CPUs and GPUs using a liquid coolant instead of traditional air cooling. " +
                "This involves installing a custom loop of tubing, reservoirs, pumps, " +
                "and radiators to circulate the coolant through the components."
        },

        {
            header: "Why Custom Water Cool?",
            body: "The benefits of custom water cooling include better temperature management, quieter operation, and the ability to overclock components " +
                "for better performance. However, it can be more expensive and requires more maintenance than traditional air cooling. " +
                "It is a popular choice for enthusiasts and gamers who want to push their systems to the limit."
        },
    ],

    gettingStartedItems: [
        {
            title: "Water Blocks:",
            body: "The water block is the component that sits on top of the CPU or GPU and transfers heat from the\n" +
                "component to the liquid coolant. When choosing a water block, make sure it is compatible with your specific CPU or GPU model.\n" +
                "You'll also want to consider the block's material (copper, nickel, or brass), as well as its performance and cost."
        },

        {
            title: "Radiator:",
            body: "The radiator is responsible for dissipating the heat from the coolant, so it's an important component to consider. When choosing a radiator, make sure it fits in your case and has enough capacity to handle the heat generated by your components. You'll also want to consider the number of fins per inch (FPI), as well as the thickness of the radiator."
        },

        {
            title: "Pump:",
            body: "The pump is responsible for circulating the coolant through the loop. When choosing a pump, make sure it has enough flow rate to handle the size of your loop and the components you're cooling. You'll also want to consider the noise level of the pump, as well as its reliability and cost."
        },

        {
            title: "Tubing:",
            body: "The tubing connects the various components in your loop. When choosing tubing, make sure it has the right diameter for your fittings and components. You'll also want to consider the material (soft or hard tubing), as well as its flexibility and durability."
        },

        {
            title: "Coolant:",
            body: "The coolant is the liquid that transfers heat from the components to the radiator. When choosing a coolant, make sure it is compatible with your components and does not contain any harmful additives that could damage your loop. You'll also want to consider the color and UV-reactivity of the coolant, as well as its performance and cost."
        },

    ],


    srConfig: (delay = 200, viewFactor = 0.25) => ({
        origin: 'bottom',
        distance: '20px',
        duration: 500,
        delay,
        rotate: { x: 0, y: 0, z: 0 },
        opacity: 0,
        scale: 1,
        easing: 'cubic-bezier(0.645, 0.045, 0.355, 1)',
        mobile: true,
        reset: false,
        useDelay: 'always',
        viewFactor,
        viewOffset: { top: 0, right: 0, bottom: 0, left: 0 },
    }),
};