import React, {useEffect, useRef} from "react";
import {LandingHeaderItem, LandingDiv, LandingHeader, LandingSection, Main} from "../styled/Landing";
import sr from "../utils/ScrollReveal";
import {srConfig} from "../config";

const GettingStarted = () => {
    const revealContainer = useRef(null)

    useEffect(() => {
        sr.reveal(revealContainer.current, srConfig())
    }, [])

    return(
            <LandingSection id="get-started" ref={revealContainer}>
                <LandingDiv>
                    <LandingHeader>
                        <h1>Getting Started</h1>
                        <LandingHeaderItem>
                            <h2>Choosing Components</h2>
                            <p>When it comes to choosing components for your water-cooling setup, there are several factors to consider,
                                including compatibility, performance, and budget. Here are some tips to help you make the right choices:</p>
                            <ul>
                                <li>
                                    <span>Water Blocks:</span> The water block is the component that sits on top of the CPU or GPU and transfers heat from the
                                    component to the liquid coolant. When choosing a water block, make sure it is compatible with your specific CPU or GPU model.
                                    You'll also want to consider the block's material (copper, nickel, or brass), as well as its performance and cost.
                                </li>
                                <li>
                                    <span>Radiator:</span> The radiator is responsible for dissipating the heat from the coolant, so it's an important component to consider.
                                    When choosing a radiator, make sure it fits in your case and has enough capacity to handle the heat generated by your components. You'll
                                    also want to consider the number of fins per inch (FPI), as well as the thickness of the radiator.
                                </li>
                                <li>
                                    <span>Pump:</span> The pump is responsible for circulating the coolant through the loop. When choosing a pump, make sure it has enough
                                    flow rate to handle the size of your loop and the components you're cooling. You'll also want to consider the noise level of the pump,
                                    as well as its reliability and cost.
                                </li>
                                <li>
                                    <span>Tubing:</span> The tubing connects the various components in your loop. When choosing tubing, make sure it has the right diameter for
                                    your fittings and components. You'll also want to consider the material (soft or hard tubing), as well as its flexibility and durability.
                                </li>
                                <li>
                                    <span>Coolant:</span> The coolant is the liquid that transfers heat from the components to the radiator. When choosing a coolant, make sure
                                    it is compatible with your components and does not contain any harmful additives that could damage your loop. You'll also want to consider the
                                    color and UV-reactivity of the coolant, as well as its performance and cost.
                                </li>
                            </ul>
                            <p>By considering these factors when choosing your components, you can ensure that your water-cooling setup is compatible, efficient, and effective.
                                Be sure to do your research and choose components that are reliable and high-quality to ensure the best performance and longevity.
                            </p>
                        </LandingHeaderItem>
                    </LandingHeader>
                </LandingDiv>
            </LandingSection>
    )
}

export default GettingStarted

